FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=Htlwrn_1

ARG COMMIT_TIMESTAMP=unknown
USER root

COPY databases/ /build/databases/
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN printf '%s' "${COMMIT_TIMESTAMP}" > /commit_timestamp.txt && \
    ls /build/databases/ | sort > /available_databases.txt

EXPOSE 1433
ENTRYPOINT ["/entrypoint.sh"]
